/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.mightyteegar.MinecraftBackup;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URI;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.FileVisitResult;
import static java.nio.file.FileVisitResult.CONTINUE;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dave
 */
public class RestoreForm extends javax.swing.JFrame {
    
    private HomeForm homeForm = new HomeForm();
    List<JCheckBox> listOfSaves = new ArrayList<JCheckBox>();
    RestoreForm rf = this;

    /**
     * Creates new form RestoreForm2
     */
    public RestoreForm() {
        initComponents();
        
        MinecraftBackup mb = new MinecraftBackup();
        mb.jframeInit(this);
        setTxfSavesPathText(mb.getMcSavePath());
        this.btnBeginRestore.setEnabled(false);
        pack();
        setLocationRelativeTo(null);  // *** this will center your app ***
        
        setVisible(true);
    }
    
    public void setTxfSavesPathText(String text) {
        this.txfRestoreSavesPath.setText(text);
    }
    
    public void setRestoreCheckboxes() {
        
       this.jpnlSubSelectSavefiles.removeAll();
       for (JCheckBox saveBox : this.listOfSaves) {
           
           saveBox.setName(saveBox.getText());
           this.jpnlSubSelectSavefiles.add(saveBox);
           saveBox.setSelected(true);
           saveBox.setVisible(true);
            
        }
        pack();
        
    }
    
    public void doSavesRestore() throws IOException {
        Path zipFilePath = Paths.get(txfRestoreSourceFile.getText());
        Path restoreSavesPath = Paths.get(txfRestoreSavesPath.getText());
        try (FileSystem zipfs = FileSystems.newFileSystem(zipFilePath, null)) {
            Path zipStartPath = zipfs.getPath("/");
            
            boolean isOverwriteOk;
            isOverwriteOk = false;
            
            savesLoop:
            for (JCheckBox jc : this.listOfSaves) {
                
                Path jcTestPath = zipfs.getPath("/" + jc.getText());
                if (Files.exists(jcTestPath)) {
                    Path currRestorePath = Paths.get(restoreSavesPath.toString() + jcTestPath.toString());
                    if (Files.exists(currRestorePath)) {
                        if (!isOverwriteOk) {
                            
                            final JOptionPane joptConfirmOverwrite = new JOptionPane();
                            Object[] options = {"Overwrite","Cancel"};
                            int opt = joptConfirmOverwrite.showOptionDialog(
                                    rf,
                                    "You are about to restore one or more savefiles that already exist. Continue?",
                                    "Confirm Overwrite",
                                    JOptionPane.YES_NO_OPTION,
                                    JOptionPane.WARNING_MESSAGE,
                                    null,
                                    options,
                                    options[1]);
                            if (opt == 0) {
                                isOverwriteOk = true;
                                
                            }
                            if (opt == 1) {
                                break savesLoop;
                            };
                            
                                                      
                        }
                        if (isOverwriteOk) {
                            
                        }
                        System.out.println("RESTORE PATH EXISTS: " + currRestorePath.toString());
                    }
                }
            }
        } 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMbRestoreHeader = new javax.swing.JLabel();
        lblRestoreDescription = new javax.swing.JLabel();
        txfRestoreSourceFile = new javax.swing.JTextField();
        btnSelectSourceFile = new javax.swing.JButton();
        lblRestoreSourceDirections = new javax.swing.JLabel();
        jcbxSelectAllSaves = new javax.swing.JCheckBox();
        txfRestoreSavesPath = new javax.swing.JTextField();
        jbtnBrowseRestoreTarget = new javax.swing.JButton();
        lblRestorePathInfo = new javax.swing.JLabel();
        btnBeginRestore = new javax.swing.JButton();
        jscpSelectSavefiles = new javax.swing.JScrollPane();
        jpnlSubSelectSavefiles = new javax.swing.JPanel();
        jbtnGoHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMbRestoreHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/mightyteegar/MinecraftBackup/images/mcrestore_header.png"))); // NOI18N

        lblRestoreDescription.setText("Restore Minecraft savefiles to your profile folder from a previous backup.");

        txfRestoreSourceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfRestoreSourceFileActionPerformed(evt);
            }
        });

        btnSelectSourceFile.setText("Select");
        btnSelectSourceFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectSourceFileMouseClicked(evt);
            }
        });
        btnSelectSourceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSourceFileActionPerformed(evt);
            }
        });

        lblRestoreSourceDirections.setFont(new java.awt.Font("Noto Sans", 2, 12)); // NOI18N
        lblRestoreSourceDirections.setText("Select a backup file to restore from");

        jcbxSelectAllSaves.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbxSelectAllSaves.setText("Select/Deselect All");
        jcbxSelectAllSaves.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbxSelectAllSavesItemStateChanged(evt);
            }
        });
        jcbxSelectAllSaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxSelectAllSavesActionPerformed(evt);
            }
        });

        txfRestoreSavesPath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfRestoreSavesPathFocusLost(evt);
            }
        });
        txfRestoreSavesPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfRestoreSavesPathActionPerformed(evt);
            }
        });

        jbtnBrowseRestoreTarget.setText("Browse");
        jbtnBrowseRestoreTarget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBrowseRestoreTargetMouseClicked(evt);
            }
        });
        jbtnBrowseRestoreTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseRestoreTargetActionPerformed(evt);
            }
        });

        lblRestorePathInfo.setFont(new java.awt.Font("Noto Sans", 2, 12)); // NOI18N
        lblRestorePathInfo.setText("(Optional) Choose a directory to restore to; defaults to your Minecraft profile folder");

        btnBeginRestore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBeginRestore.setText("Begin Restore");
        btnBeginRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBeginRestoreMouseClicked(evt);
            }
        });
        btnBeginRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeginRestoreActionPerformed(evt);
            }
        });

        jpnlSubSelectSavefiles.setName(""); // NOI18N
        jpnlSubSelectSavefiles.setLayout(new javax.swing.BoxLayout(jpnlSubSelectSavefiles, javax.swing.BoxLayout.PAGE_AXIS));
        jscpSelectSavefiles.setViewportView(jpnlSubSelectSavefiles);

        jbtnGoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/mightyteegar/MinecraftBackup/images/home_icon.png"))); // NOI18N
        jbtnGoHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnGoHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMbRestoreHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jscpSelectSavefiles, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txfRestoreSavesPath)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnBrowseRestoreTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txfRestoreSourceFile, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRestoreDescription, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSelectSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jbtnGoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBeginRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRestoreSourceDirections)
                            .addComponent(lblRestorePathInfo)
                            .addComponent(jcbxSelectAllSaves))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMbRestoreHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRestoreDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectSourceFile)
                            .addComponent(txfRestoreSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnGoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestoreSourceDirections)
                .addGap(18, 18, 18)
                .addComponent(jcbxSelectAllSaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpSelectSavefiles, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfRestoreSavesPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBrowseRestoreTarget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestorePathInfo)
                .addGap(18, 18, 18)
                .addComponent(btnBeginRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfRestoreSourceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfRestoreSourceFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfRestoreSourceFileActionPerformed

    private void btnSelectSourceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSourceFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectSourceFileActionPerformed

    private void txfRestoreSavesPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfRestoreSavesPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfRestoreSavesPathActionPerformed

    private void jbtnBrowseRestoreTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseRestoreTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBrowseRestoreTargetActionPerformed

    private void btnSelectSourceFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectSourceFileMouseClicked
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser();
        jc.setPreferredSize(new Dimension(700,400));
        jc.setDialogTitle("Minecraft backup archive location");
        jc.setDialogType(JFileChooser.SAVE_DIALOG);
        jc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int returnVal = jc.showSaveDialog(RestoreForm.this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            rf.listOfSaves.clear();
            txfRestoreSourceFile.setText(jc.getSelectedFile().getAbsolutePath());
            Path zipFilePath = Paths.get(txfRestoreSourceFile.getText());
            try (FileSystem zipfs = FileSystems.newFileSystem(zipFilePath, null)) {
                Path zipStartPath = zipfs.getPath("/");
                
                Files.walkFileTree(zipStartPath, new SimpleFileVisitor<Path>() {
                    
                    int i = 0;
                    
                    public FileVisitResult preVisitDirectory(Path p, BasicFileAttributes attrs) {
                        
                        if (!p.toString().equals("/")) {
                            
                            if (p.getParent().toString().equals("/")) {
                                
                                Path levelDatPath = zipfs.getPath(p + "level.dat");
                                Path regionPath = zipfs.getPath(p + "region");
                                Path playerdataPath = zipfs.getPath(p + "playerdata");
                                if (Files.exists(levelDatPath) &&
                                    Files.exists(regionPath) &&
                                    Files.exists(playerdataPath)) {
                                    // File is a valid Minecraft backup archive
                                    rf.listOfSaves.add(new JCheckBox());
                                    rf.listOfSaves.get(i).setText(p.toString().replace("/", ""));
                                    i++;
                                }
                                
                                
                            }
                        }
                        return CONTINUE; 
                    }
                    
                    public FileVisitResult visitFileFailed(Path p, IOException e) {
                        System.out.println(p.toString() + ": File visit failed, attempting to continue...");
                        return CONTINUE;
                    }
            });
            } 
            catch (NoSuchFileException nfe) {
                System.out.println("No such file exception found");
                Logger.getLogger(RestoreForm.class.getName()).log(Level.SEVERE, null, nfe);
                // continue
            }
            catch (IOException ex) {
                System.out.println("ERROR");
                Logger.getLogger(RestoreForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (rf.listOfSaves.size() == 0) {
                this.btnBeginRestore.setEnabled(false);
                this.txfRestoreSourceFile.setBackground(Color.PINK);
                this.lblRestoreSourceDirections.setForeground(Color.red);
                this.lblRestoreSourceDirections.setText("Selected file is not a valid Minecraft backup");
            }
            else {
                this.txfRestoreSourceFile.setBackground(Color.white);
                this.lblRestoreSourceDirections.setForeground(Color.black);
                this.lblRestoreSourceDirections.setText("Select a backup file to restore from");
                this.jcbxSelectAllSaves.setSelected(true);                
                this.btnBeginRestore.setEnabled(true);
            }
            this.setRestoreCheckboxes();
        }
    }//GEN-LAST:event_btnSelectSourceFileMouseClicked

    private void jcbxSelectAllSavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxSelectAllSavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxSelectAllSavesActionPerformed

    private void jcbxSelectAllSavesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbxSelectAllSavesItemStateChanged
        if (this.jcbxSelectAllSaves.isSelected()) {
            for (JCheckBox jc : this.listOfSaves) {
                jc.setSelected(true);
            }
        }
        else {
            for (JCheckBox jc : this.listOfSaves) {
                jc.setSelected(false);
            }
        }        
    }//GEN-LAST:event_jcbxSelectAllSavesItemStateChanged

    private void btnBeginRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeginRestoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBeginRestoreActionPerformed

    private void btnBeginRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeginRestoreMouseClicked
        try {
            // TODO add your handling code here:
            doSavesRestore();
        } catch (IOException ex) {
            Logger.getLogger(RestoreForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBeginRestoreMouseClicked

    private void jbtnBrowseRestoreTargetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBrowseRestoreTargetMouseClicked
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser();
        jc.setPreferredSize(new Dimension(700,400));
        jc.setDialogTitle("Minecraft saves restore location");
        jc.setDialogType(JFileChooser.SAVE_DIALOG);
        jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int returnVal = jc.showSaveDialog(RestoreForm.this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txfRestoreSavesPath.setText(jc.getSelectedFile().getAbsolutePath());
            if (txfRestoreSavesPath.getBackground().equals(Color.pink)) {
                txfRestoreSavesPath.setBackground(Color.white);
                txfRestoreSavesPath.setForeground(Color.black);
                lblRestorePathInfo.setText("(Optional) Choose a directory to restore to; defaults to your Minecraft profile folder");
            }
        }
        
    }//GEN-LAST:event_jbtnBrowseRestoreTargetMouseClicked

    private void txfRestoreSavesPathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfRestoreSavesPathFocusLost
        // TODO add your handling code here:
        // check the path and make sure it's valid
        Path p = Paths.get(txfRestoreSavesPath.getText());
        if (!Files.exists(p)) {
            txfRestoreSavesPath.setBackground(Color.PINK);
            txfRestoreSavesPath.setForeground(Color.red);
            lblRestorePathInfo.setText("Path does not exist, choose a different location");
        }
        else {
            txfRestoreSavesPath.setBackground(Color.white);
            txfRestoreSavesPath.setForeground(Color.black);
            lblRestorePathInfo.setText("(Optional) Choose a directory to restore to; defaults to your Minecraft profile folder");
        }
    }//GEN-LAST:event_txfRestoreSavesPathFocusLost

    private void jbtnGoHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGoHomeMouseClicked
        // TODO add your handling code here:
        this.homeForm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbtnGoHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeginRestore;
    private javax.swing.JButton btnSelectSourceFile;
    private javax.swing.JButton jbtnBrowseRestoreTarget;
    private javax.swing.JButton jbtnGoHome;
    private javax.swing.JCheckBox jcbxSelectAllSaves;
    private javax.swing.JPanel jpnlSubSelectSavefiles;
    private javax.swing.JScrollPane jscpSelectSavefiles;
    private javax.swing.JLabel lblMbRestoreHeader;
    private javax.swing.JLabel lblRestoreDescription;
    private javax.swing.JLabel lblRestorePathInfo;
    private javax.swing.JLabel lblRestoreSourceDirections;
    private javax.swing.JTextField txfRestoreSavesPath;
    private javax.swing.JTextField txfRestoreSourceFile;
    // End of variables declaration//GEN-END:variables
}
